# Dockerfile to create new image in case there is update to repo code only
FROM public.ecr.aws/niaid_nephele/pipeline/nephele_sars2_base:5a51406

ARG MGMT_ACCT_ID

# Install nephele_pipeline_utils
RUN --mount=type=secret,id=AWS_ACCESS_KEY_ID \
    --mount=type=secret,id=AWS_SECRET_ACCESS_KEY \
    --mount=type=secret,id=AWS_SESSION_TOKEN \
    AWS_ACCESS_KEY_ID=$(cat /run/secrets/AWS_ACCESS_KEY_ID) \
    AWS_SECRET_ACCESS_KEY=$(cat /run/secrets/AWS_SECRET_ACCESS_KEY) \
    AWS_SESSION_TOKEN=$(cat /run/secrets/AWS_SESSION_TOKEN) \
    aws codeartifact login --tool pip --repository nephele_workspace --domain pypi --domain-owner ${MGMT_ACCT_ID} --region us-east-1
RUN pip install nephele-pipeline-utils==0.1.55


# Set the working directory for the pipeline
WORKDIR /pipeline

COPY nephele_sars2 .

# Define the entrypoint and command
ENTRYPOINT ["python", "main.py"]
CMD ["--help"]