# Builds image and pushes to ECR in mgmt space in public registry domain.
name: Build and Push Docker Image to AWS ECR

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Git branch to containerize"
        required: true
        default: "main"
      dockerfile:
        # Dockerfile.update if only repo code is updated. Else, Dockerfile
        description: "Docker file to use"
        required: true
        default: "Dockerfile.update"
      tag:
        description: "Docker image version tag"
        required: true
        default: "latest"

env:
  PIPELINE: nephele_sars2
  REG: us-east-1

jobs:
  build-and-push:
    runs-on: self-hosted-ws

    steps:
      - name: Determine branch and tag (on workflow_dispatch)
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "BRANCH=${{ github.event.inputs.branch }}" >> $GITHUB_ENV
          echo "IMAGE_VERSION_TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          echo "DOCKERFILE=${{ github.event.inputs.dockerfile }}" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }}

      - name: Get git SHA
        run: |
          echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Get Account
        id: get_account
        run: |
          echo "MGMT_ACCT_ID=$(aws ssm get-parameter --with-decryption --name "/monarch-ro/space-accounts/mgmt" --region ${{ env.REG }} --query "Parameter.Value" --output text)" >> $GITHUB_ENV

      - name: Login to AWS ECR
        run: |
          echo "IMG=public.ecr.aws/niaid_nephele/pipeline/${{ env.PIPELINE }}" >> $GITHUB_ENV
          aws ecr-public get-login-password --region ${{ env.REG }} | docker login --username AWS --password-stdin public.ecr.aws/niaid_nephele

      - name: Build and tag Docker image
        env:
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ env.AWS_SESSION_TOKEN }}
        run: |
          docker build -f ${{ env.DOCKERFILE }} --tag ${{ env.IMG }}:${{ env.SHA }} --tag ${{ env.IMG }}:${{ env.IMAGE_VERSION_TAG }} --secret id=AWS_ACCESS_KEY_ID --secret id=AWS_SECRET_ACCESS_KEY --secret id=AWS_SESSION_TOKEN --build-arg MGMT_ACCT_ID=${{ env.MGMT_ACCT_ID }} .

      - name: Push Docker image to ECR
        run: |
          docker push ${{ env.IMG }}:${{ env.SHA }}
          docker push ${{ env.IMG }}:${{ env.IMAGE_VERSION_TAG }}
