# Builds image and pushes to ECR in mgmt space in public registry domain.
name: Build and Push Docker Image to AWS ECR
run-name: Build and Push Docker Image to AWS ECR (SHA ${{ github.sha }})

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Docker image version tag. Provide the version in config.json. The version has to be newer than the one that is currently in production."
        required: true

jobs:
  build-and-push:
    uses: niaid/nephele_gh_actions/.github/workflows/build-and-push.yaml@main
    with:
      pipeline: nephele_sars2
      tag: ${{ inputs.tag }}
      region: us-east-1