# Builds base image and pushes to ECR in mgmt space in public registry domain.
name: Build and Push Base Docker Image to AWS ECR
run-name: Build and Push Base Docker Image to AWS ECR (SHA ${{ github.sha }})

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Docker image version tag"
        required: true
        default: "latest"

jobs:
  build-and-push:
    uses: niaid/nephele_gh_actions/.github/workflows/build-and-push-base-image.yaml@main
    with:
      pipeline: nephele_sars2
      tag: ${{ inputs.tag }}
      region: us-east-1
