# Used to set image pointer for dev/qa/prod.
name: Set latest image pointer in parameter store
run-name: Set latest image pointer in parameter store for ${{ inputs.env }} (SHA ${{ inputs.sha == '' && github.sha || inputs.sha }})

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment to set image pointer to"
        required: true
        default: "dev"
        type: choice
        options:
          - "dev"
          - "qa"
          - "prod"
      # Git commit SHA with which the docker image was tagged. If not provided, will use the SHA of the latest commit.
      # sha is useful as user input during workflow run in case the latest commit is ahead of the commit in the docker image.
      sha:
        description: "Git commit SHA with which the docker image was tagged"
        required: false
        default: ""

jobs:
  set-image-pointer:
    uses: niaid/nephele_gh_actions/.github/workflows/set-image-pointer.yaml@main
    with:
      pipeline: nephele_sars2
      region: us-east-1
      env: ${{ inputs.env }}
      sha: ${{ inputs.sha }}
