# Updates ECR metadata/documentation without rebuilding the image
name: Update ECR Documentation

on:
  workflow_dispatch:

jobs:
  update-ecr-metadata:
    uses: niaid/nephele_gh_actions/.github/workflows/update-ecr-metadata.yaml@main
    with:
      pipeline: nephele_sars2
      description: "SARS-CoV-2 analysis pipeline for Nephele - genome assembly and mutation calling from Illumina amplicon sequencing data"
      region: us-east-1
